spring:
  application:
    name: App
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: https://grook-production.up.railway.app/login/oauth2/code/azure
            authorization-grant-type: authorization_code
            client-name: Azure B2C
            provider: azure
        provider:
          azure:
            authorization-uri: ${AZURE_AUTH_URI}
            token-uri: ${AZURE_TOKEN_URI}
            user-info-uri: ${AZURE_USER_INFO_URI}
            user-name-attribute: name

server:
  port: ${PORT:8080}
  forward-headers-strategy: native
  servlet:
    context-path: /

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: ${PORT:8080}
