spring:
  application:
    name: App
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ec8b2417-1b7d-4236-b2b3-d79d0516e462
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: https://grook-production.up.railway.app/login/oauth2/code/azure
            authorization-grant-type: authorization_code
            client-name: Azure B2C
            provider: azure-b2c
        provider:
          azure-b2c:
            authorization-uri: https://volvogroupiddev.b2clogin.com/volvogroupiddev.onmicrosoft.com/B2C_1A_FG_HCL_SIGNUP_SIGNIN/oauth2/v2.0/authorize
            token-uri: https://volvogroupiddev.b2clogin.com/volvogroupiddev.onmicrosoft.com/B2C_1A_FG_HCL_SIGNUP_SIGNIN/oauth2/v2.0/token
            jwk-set-uri: https://volvogroupiddev.b2clogin.com/volvogroupiddev.onmicrosoft.com/B2C_1A_FG_HCL_SIGNUP_SIGNIN/discovery/v2.0/keys
            user-info-uri: https://volvogroupiddev.b2clogin.com/volvogroupiddev.onmicrosoft.com/B2C_1A_FG_HCL_SIGNUP_SIGNIN/openid/userinfo
            user-name-attribute: name

server:
  port: ${PORT:8080}
  forward-headers-strategy: NATIVE
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    context-path: /

# Logging configuration
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.Grook.App: DEBUG
  # Configure console output
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss}] [${spring.application.name}] [%thread] %-5level %logger{36} - %msg%n'
  # Ensure logs go to console
  file:
    name: /dev/stdout

app:
  home-url: https://grook-production.up.railway.app

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
app:
  home-url: http://localhost:8080

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: ${PORT:8080}
app:
  home-url: https://grook-production.up.railway.app
