spring:
  application:
    name: App

server:
  port: ${PORT:8080}
  forward-headers-strategy: NATIVE
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    context-path: /

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.Grook.App: DEBUG
  # Configure console output
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss}] [${spring.application.name}] [%thread] %-5level %logger{36} - %msg%n'
  # Ensure logs go to console
  file:
    name: /dev/stdout

app:
  home-url: https://grook-production.up.railway.app

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
app:
  home-url: http://localhost:8080

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: ${PORT:8080}
app:
  home-url: https://grook-production.up.railway.app
